#!/usr/bin/env python3
#
# Add a task to taskwarrior via email. Makes use of the taskw Python bindings.
#
# http://taskwarrior.org
# https://github.com/ralphbean/taskw
#
# See README for more info.
#

from taskw import TaskWarrior
import time
import email
import fileinput

msg_string = ""
for line in fileinput.input():
  msg_string += line

msg = email.message_from_string(msg_string)
subject = email.header.make_header(email.header.decode_header(msg.get("Subject")))

tdesc = str(subject).strip()
tdue = str(int(time.time()))

w = TaskWarrior()
w.task_add(tdesc, due=tdue)
